// Skills data rendered in the editor pane as `src/skills.json`.
export const SKILL_MAX = 5;

export const skills = {
  languages: {
    TypeScript: 4,
    JavaScript: 5,
    PHP: 5,
    Python: 4,
    SQL: 5,
    "System Design": 4,
  } as Record<string, number>,
  management: [
    "Leading Teams",
    "Scrum Master",
    "Agile Methodologies",
    "Effective Communication",
  ],
  frontend: [
    "React.js",
    "Next.js",
    "Vue.js",
    "CSS (Tailwind, shadcn/ui)",
    "Redux",
    "React Native",
  ],
  backend: [
    "Node.js",
    "Express",
    "Laravel",
    "Nest.js",
    "FastAPI",
    "API Development (REST, GraphQL)",
    "Algolia",
    "OAuth2",
  ],
  databases: [
    "Postgres",
    "MySQL",
    "SQLite",
    "DynamoDB",
    "MongoDB",
    "Supabase",
    "Redis",
    "Memcached",
  ],
  devops: [
    "AWS (S3, EC2, Serverless, Events, Messaging)",
    "Docker",
    "Kubernetes",
    "CI/CD (Jenkins)",
    "IaC",
    "Terraform",
    "Sceptre",
    "Git",
    "Bitbucket",
    "Nginx",
    "Apache",
    "Unit Testing (Jest, Mocha, Selenium)",
    "Microservices",
  ],
  ai: ["Claude", "Gemini", "OpenAI"],
};
